### ISSUE TITLE
gobble: Data Validation causes MemoryError

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1141]
```
2016-10-13T22:58:50.086481329Z [2016-10-13 22:58:50,086: INFO/Worker-5] fiscal.upload: Traceback (most recent call last):
2016-10-13T22:58:50.089248405Z [2016-10-13 22:58:50,086: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/datapackage_pipelines/manager/../lib/fiscal/upload.py", line 23, in <module>
2016-10-13T22:58:50.089261704Z [2016-10-13 22:58:50,086: INFO/Worker-5] fiscal.upload:     package.upload()
2016-10-13T22:58:50.089268582Z [2016-10-13 22:58:50,086: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/gobble/fiscal.py", line 160, in upload
2016-10-13T22:58:50.089274279Z [2016-10-13 22:58:50,086: INFO/Worker-5] fiscal.upload:     self.validate()
2016-10-13T22:58:50.089279493Z [2016-10-13 22:58:50,087: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/gobble/fiscal.py", line 131, in validate
2016-10-13T22:58:50.089285367Z [2016-10-13 22:58:50,087: INFO/Worker-5] fiscal.upload:     return self._validate_data(raise_on_error)
2016-10-13T22:58:50.089313622Z [2016-10-13 22:58:50,087: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/gobble/fiscal.py", line 250, in _validate_data
2016-10-13T22:58:50.089320033Z [2016-10-13 22:58:50,087: INFO/Worker-5] fiscal.upload:     pipeline = Pipeline(filepath, report_stream=StringIO())
2016-10-13T22:58:50.089326012Z [2016-10-13 22:58:50,087: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/goodtables/pipeline/pipeline.py", line 115, in __init__
2016-10-13T22:58:50.089793911Z [2016-10-13 22:58:50,087: INFO/Worker-5] fiscal.upload:     header_index=self.header_index)
2016-10-13T22:58:50.089808969Z [2016-10-13 22:58:50,088: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/goodtables/datatable/datatable.py", line 45, in __init__
2016-10-13T22:58:50.089814845Z [2016-10-13 22:58:50,088: INFO/Worker-5] fiscal.upload:     self.stream = self.to_textstream(self.data_source)
2016-10-13T22:58:50.089824345Z [2016-10-13 22:58:50,088: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/goodtables/datatable/datatable.py", line 138, in to_textstream
2016-10-13T22:58:50.089829702Z [2016-10-13 22:58:50,089: INFO/Worker-5] fiscal.upload:     self.encoding = self._detect_stream_encoding(stream)
2016-10-13T22:58:50.089846251Z [2016-10-13 22:58:50,089: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/goodtables/datatable/datatable.py", line 238, in _detect_stream_encoding
2016-10-13T22:58:50.093695139Z [2016-10-13 22:58:50,089: INFO/Worker-5] fiscal.upload:     self._check_for_unsupported_format(stream)
2016-10-13T22:58:50.093864981Z [2016-10-13 22:58:50,093: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/goodtables/datatable/datatable.py", line 334, in _check_for_unsupported_format
2016-10-13T22:58:50.094024515Z [2016-10-13 22:58:50,093: INFO/Worker-5] fiscal.upload:     if  getattr(self, '_stream_is_{0}'.format(file_format))(test_stream):
2016-10-13T22:58:50.094185442Z [2016-10-13 22:58:50,093: INFO/Worker-5] fiscal.upload:   File "/usr/lib/python3.5/site-packages/goodtables/datatable/datatable.py", line 299, in _stream_is_html
2016-10-13T22:58:50.094342065Z [2016-10-13 22:58:50,094: INFO/Worker-5] fiscal.upload:     _sample = test_stream.read()
2016-10-13T22:58:50.094573094Z [2016-10-13 22:58:50,094: INFO/Worker-5] fiscal.upload: MemoryError
```

**Comment by akariv** [comment]
I disabled validation and it sorted this issue out.
