### ISSUE TITLE
Gobble: package.json not found

### ISSUE THREAD

**Issue by cyberbikepunk** [openspending/openspending#1153]
```
Traceback (most recent call last):
  File "/home/loic/.virtualenvs/dpp/bin/gobble", line 7, in <module>
    from gobble.cli import gobble
  File "/home/loic/.virtualenvs/dpp/lib/python3.5/site-packages/gobble/cli.py", line 47, in <module>
    version=_get_package('version'),
  File "/home/loic/.virtualenvs/dpp/lib/python3.5/site-packages/gobble/cli.py", line 40, in _get_package
    with io.open(filepath) as json:
FileNotFoundError: [Errno 2] No such file or directory: '/home/loic/.virtualenvs/dpp/lib/python3.5/site-packages/package.json'
```
This happens when the command line is invoked.

**Comment by pwalsh** [comment]
Moved to https://github.com/openspending/openspending/issues/1326
