### ISSUE TITLE
Publishing data package status: datapackage.json - Failed

### ISSUE THREAD

**Issue by Hazwany** [openspending/openspending#1155]
I encountered a HTTP Error 403 when I want to publish a data package.

![15 nov](https://cloud.githubusercontent.com/assets/11497391/20298873/2d8d381c-ab53-11e6-8b6f-7a6940b7b776.png)

When I check from OS Admin, the dataset that was recently failed to published is in the list of datasets.

![15 nov_2](https://cloud.githubusercontent.com/assets/11497391/20298953/99c3eea4-ab53-11e6-890f-90ee0179cf7a.png)

The content of the dataset is empty.

![15 nov_3](https://cloud.githubusercontent.com/assets/11497391/20298997/ccda5814-ab53-11e6-8926-16d453026d49.png)

I believe in Step 2 after I upload the csv file, I have mapped as accurately as possible for all respective columns.

The chrome browser that is running is incognito. Would that cause the error to exist?

Kindly advise.

**Comment by akariv** [comment]
Hi,

Can you please try and repeat the operation from scratch and see if the
problem persists?
If it does, can you try and remove spaces from the filename and retry?

**Comment by Hazwany** [comment]
@akariv I have tried again based on your suggestions but I am facing the same problem.

![15 nov_4](https://cloud.githubusercontent.com/assets/11497391/20299899/bf4dc614-ab57-11e6-9a52-c477d1116573.png)

**Comment by akariv** [comment]
I honestly can't find any issue with the file...
What happens if you retry pressing 'publish' after you see this message?

**Comment by sweemeng** [comment]
I still faces the same error with the same dataset

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/tabulator/loaders/web.py", line 40, in load
    bytes = _WebStream(source)
  File "/usr/lib/python3.5/site-packages/tabulator/loaders/web.py", line 74, in __init__
    self.__response = urlopen(self.__source)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/datapackage/resource.py", line 292, in iter
    headers=1, encoding=encoding, **options).open()
  File "/usr/lib/python3.5/site-packages/tabulator/stream.py", line 185, in open
    self.__parser.open(self.__source, self.__encoding, self.__loader)
  File "/usr/lib/python3.5/site-packages/tabulator/parsers/csv.py", line 54, in open
    self.__chars = loader.load(source, encoding, mode='t')
  File "/usr/lib/python3.5/site-packages/tabulator/loaders/web.py", line 45, in load
    raise exceptions.HTTPError(str(exception))
tabulator.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/babbage_fiscal/loader.py", line 167, in load_fdp_to_db
    row_processor = RowProcessor(resource.iter(), status_update,
  File "/usr/lib/python3.5/site-packages/datapackage/resource.py", line 296, in iter
    six.raise_from(ValueError(msg.format(data_path_or_url)), e)
  File "<string>", line 2, in raise_from
ValueError: Data at 'https://s3.amazonaws.com:443/datastore.openspending.org/ce52c7729e68cbf48e0aafc6ddc43667/kkm2017/KKM2017.csv' isn't in a known tabular data format```

**Comment by Hazwany** [comment]
@akariv Retried the same process and re-publish again, I still face the same error. Checked console, this is what I found

![screenshot from 2016-11-15 21-36-26](https://cloud.githubusercontent.com/assets/11497391/20307720/b1eb2f92-ab7b-11e6-8ab0-4c69c929fb34.png)

**Comment by akariv** [comment]
Okay, I think I start to understand the problem.

As a _workaround_ (until this is fixed), can you try with the filename consisting only of lowercase letters?

**Comment by akariv** [comment]
(@Hazwany thank you for helping debug this issue!)

**Comment by Hazwany** [comment]
@akariv I have tried your suggestions (filename with lowercase letters) and this is what I found

![15 nov_5](https://cloud.githubusercontent.com/assets/11497391/20308625/c69fb1c0-ab7f-11e6-9002-87a2fde4f295.png)

![screenshot from 2016-11-15 22-05-35](https://cloud.githubusercontent.com/assets/11497391/20308641/db3d5024-ab7f-11e6-9272-961e80cae884.png)

**Comment by akariv** [comment]
@Hazwany this bug was already resolved (but not deployed to the server).
I now updated the server, can you please retry?

**Comment by akariv** [comment]
(just to make myself better understood - the 2nd error you encountered was already fixed. we're still working on the 1st error)

**Comment by Hazwany** [comment]
@akariv I have tried resubmit 3 same files with different filenames:

1. capital letters with spacing and a hyphen

1. without hyphen and spacing but in capital letters

1. small letters without spacing nor hyphen

Same errors occurred for all 3 respective files as shown above.

**Comment by akariv** [comment]
Ok @Hazwany we're currently looking into this problem and it will hopefully
be resolved today.

Sorry for the inconvenience.

**Comment by akariv** [comment]
@Hazwany - one of the issues was resolved: you shouldn't use a partial code in the top level of a hierarchy (specifically in your case the administrative classification).
I'm currently removing that option so that users cannot make that error in the first place.
In 30 minutes or so you can retry uploading the file (still lowercase letters please until we solve the other issue).

**Comment by kravets-levko** [comment]
@akariv @Hazwany I've found a bug, PR is coming :-)

**Comment by akariv** [comment]
fixed and deployed

**Comment by Hazwany** [comment]
@akariv @kravets-levko Thank so much for solving this issue! I can safely publish the data package!

Also, just to confirm, I found something missing while I was mapping in Step 2. I want to map a drill down for administrative public funds and below is the mapping for the first hierarchy:

Administrative Classification > Non standard Administrative Classification > Top Classification Level > Unique Identifier

Do correct me if I'm wrong, but I think there is supposed to be an additional options after Unique Identifier; Complete Identifier and Partial Identifier. This missing option only happens for the first hierarchy.

![pic 1](https://cloud.githubusercontent.com/assets/11497391/20351091/64545cfa-ac4c-11e6-9f25-014cca70972f.png)

![pic](https://cloud.githubusercontent.com/assets/11497391/20351103/6ec55be4-ac4c-11e6-940b-0a00a501ebe1.png)

**Comment by akariv** [comment]
No, that was actually part of the fix - as there's not much sense in a
partial id in three top level of a hierarchy.
By definition, top levels can only be full codes.

**Comment by Hazwany** [comment]
@akariv ok, got it. You can close this issue. Thanks again!

**Comment by fathoni** [comment]
Hi @akariv , I still found an error for  publishing the data package. I am unable to comprehend your explanation here: 

> you shouldn't use a partial code in the top level of a hierarchy (specifically in your case the administrative classification

could you please elaborate? 

I am currently publishing the dataset via http://staging.openspending.org/packager/provide-data

Here's the error I've got:

`Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/os_package_registry/package_registry.py", line 64, in get_raw
    ret = self.es.get(index='packages', doc_type='package', id=name, _source=self.PACKAGE_FIELDS)
  File "/usr/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 330, in get
    doc_type, id), params=params)
  File "/usr/lib/python3.5/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"packages","_type":"package","_id":"848b8e447d0dfc798a77ef4f3a7bbcbd:aragon-2006-expenditure-budget2","found":false}')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/babbage_fiscal/loader.py", line 88, in status_update
    self.registry.get_raw(self.model_name)
  File "/usr/lib/python3.5/site-packages/os_package_registry/package_registry.py", line 77, in get_raw
    raise KeyError(name)
KeyError: '848b8e447d0dfc798a77ef4f3a7bbcbd:aragon-2006-expenditure-budget2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/babbage_fiscal/loader.py", line 188, in load_fdp_to_db
    self.status_update(status=STATUS_CREATING_BABBAGE_MODEL)
  File "/usr/lib/python3.5/site-packages/babbage_fiscal/loader.py", line 95, in status_update
    _origin_url = self.package
AttributeError: 'FDPLoader' object has no attribute 'package'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/os_package_registry/package_registry.py", line 64, in get_raw
    ret = self.es.get(index='packages', doc_type='package', id=name, _source=self.PACKAGE_FIELDS)
  File "/usr/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 330, in get
    doc_type, id), params=params)
  File "/usr/lib/python3.5/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, '{"_index":"packages","_type":"package","_id":"848b8e447d0dfc798a77ef4f3a7bbcbd:aragon-2006-expenditure-budget2","found":false}')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/babbage_fiscal/loader.py", line 88, in status_update
    self.registry.get_raw(self.model_name)
  File "/usr/lib/python3.5/site-packages/os_package_registry/package_registry.py", line 77, in get_raw
    raise KeyError(name)
KeyError: '848b8e447d0dfc798a77ef4f3a7bbcbd:aragon-2006-expenditure-budget2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/babbage_fiscal/tasks.py", line 55, in load_fdp_task
    success = FDPLoader(get_engine()).load_fdp_to_db(package, send_progress)
  File "/usr/lib/python3.5/site-packages/babbage_fiscal/loader.py", line 231, in load_fdp_to_db
    self.status_update(status=STATUS_FAIL, error=traceback.format_exc())
  File "/usr/lib/python3.5/site-packages/babbage_fiscal/loader.py", line 95, in status_update
    _origin_url = self.package
AttributeError: 'FDPLoader' object has no attribute 'package' `

**Comment by akariv** [comment]
@fathoni the fix for @Hazwany was probably not deployed to the staging environment as well.
I did that right now, so can you please retry?

Regarding your question about partial ids - 
a partial ID is one that only makes sense in the context of a parent ID. This basically means that a top level id cannot be partial, as it has no parent level in the hierarchy.

**Comment by fathoni** [comment]
@akariv Perfect! tried it on staging and worked well. Then to confirm my 'partial ID' understanding, it just means that all top-parent dimension IDs are supposed to be defined in the dataset itself, right?
