### ISSUE TITLE
Can't run "git commit" on OS Types

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1281]
To reproduce, clone https://github.com/openspending/os-types and do `git commit`. You should see:

```
$ git commit

> os-types@0.0.0 test:single /home/vitor/Projetos/okfn/openspending/os-types
> cp src/index.test.js dist/ && istanbul cover -x *.test.js _mocha -- -R spec dist/index.test.js --compilers js:babel/register && rm dist/index.test.js

No coverage information was collected, exit without writing coverage information
module.js:328
    throw err;
    ^

Error: Cannot find module './index'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/vitor/Projetos/okfn/openspending/os-types/dist/index.test.js:3:28)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module._extensions.(anonymous function) (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/lib/hook.js:109:37)
    at istanbulLoader (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:191:3)
    at Object.require.extensions.(anonymous function) [as .js] (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/vitor/Projetos/okfn/openspending/os-types/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Object.Module._extensions.(anonymous function) (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at runFn (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/node_modules/async/lib/async.js:361:13
    at /home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/node_modules/async/lib/async.js:246:17)
    at /home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /home/vitor/Projetos/okfn/openspending/os-types/node_modules/istanbul/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1534:14)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/home/vitor/.nvm/versions/node/v4.2.6/bin/node" "/home/vitor/.nvm/versions/node/v4.2.6/bin/npm" "run" "test:single"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! os-types@0.0.0 test:single: `cp src/index.test.js dist/ && istanbul cover -x *.test.js _mocha -- -R spec dist/index.test.js --compilers js:babel/register && rm dist/index.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the os-types@0.0.0 test:single script 'cp src/index.test.js dist/ && istanbul cover -x *.test.js _mocha -- -R spec dist/index.test.js --compilers js:babel/register && rm dist/index.test.js'.
npm ERR! This is most likely a problem with the os-types package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cp src/index.test.js dist/ && istanbul cover -x *.test.js _mocha -- -R spec dist/index.test.js --compilers js:babel/register && rm dist/index.test.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls os-types
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vitor/Projetos/okfn/openspending/os-types/npm-debug.log
```

**Comment by vitorbaptista** [comment]
I just noticed by reading `.travis.yml` that I needed to run `npm run build` before `git commit`. It was surprising. I think the fix here is either let the user run the tests himself (i.e. remove the git hook), or automatically run `build` before `pretest:single`.
