### ISSUE TITLE
[OS-Packager] Build fails on d3-time-format requirement

### ISSUE THREAD

**Issue by skarampatakis** [openspending/openspending#1290]
I cloned latest version from master repo, did ```npm install``` and then ```npm run build``` but I get this error
```
npm run build

> fiscal-data-packager@0.0.1 build ~/NetBeansProjects/os-packager
> gulp

[07:17:01] Using gulpfile ~/NetBeansProjects/os-packager/gulpfile.js
[07:17:01] Starting 'scripts.application'...
[07:17:01] Starting 'styles.vendor'...
[07:17:01] Starting 'styles.application'...
[07:17:01] Starting 'assets.fonts'...
[07:17:01] Starting 'assets.images'...
[07:17:01] Starting 'assets.favicon'...
[07:17:01] Finished 'assets.favicon' after 430 ms
[07:17:01] Finished 'styles.application' after 449 ms
[07:17:01] Finished 'styles.vendor' after 465 ms
[07:17:01] Starting 'styles'...
[07:17:01] Finished 'styles' after 16 μs
[07:17:02] Finished 'assets.images' after 516 ms
[07:17:03] Finished 'assets.fonts' after 1.81 s
[07:17:03] Starting 'assets'...
[07:17:03] Finished 'assets' after 7.57 μs
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'd3-time-format' from '~/NetBeansProjects/os-packager/node_modules/jsontableschema'
    at ~/NetBeansProjects/os-packager/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (~/NetBeansProjects/os-packager/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (~/NetBeansProjects/os-packager/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (~/NetBeansProjects/os-packager/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (~/NetBeansProjects/os-packager/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at ~/NetBeansProjects/os-packager/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 4.4.0-81-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! fiscal-data-packager@0.0.1 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fiscal-data-packager@0.0.1 build script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fiscal-data-packager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fiscal-data-packager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fiscal-data-packager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/NetBeansProjects/os-packager/npm-debug.log
```

So to installed manually this module by
```
npm install d3-time-format
```

and the build finished successfully. So there might be a missing dependency?

**Comment by pwalsh** [comment]
@akariv can you please fix.

**Comment by akariv** [comment]
Latest version builds with this configuration:
```
$ node --version
v8.7.0
$ npm --version
5.4.2
```
