### ISSUE TITLE
URL not found: https://openspending.org/api/3/info/images/apple-touch-icon.png/package

### ISSUE THREAD

**Issue by vitorbaptista** [openspending/openspending#1307]
In our logs, we have:

```
Aug 19 15:38:39 os-viewer-1 os-viewer-1.production.1e1f5d3e: Trace: Error: Failed loading data from https://openspending.org/api/3/info/images/apple-touch-icon.png/package
Aug 19 15:38:39 os-viewer-1 os-viewer-1.production.1e1f5d3e:     at /app/app/services/utils.js:38:15
Aug 19 15:38:39 os-viewer-1 os-viewer-1.production.1e1f5d3e:     at process._tickCallback (internal/process/next_tick.js:109:7)
Aug 19 15:38:39 os-viewer-1 os-viewer-1.production.1e1f5d3e:     at /app/app/services/utils.js:43:15
Aug 19 15:38:39 os-viewer-1 os-viewer-1.production.1e1f5d3e:     at process._tickCallback (internal/process/next_tick.js:109:7)
```

This came from https://github.com/openspending/os-viewer/blob/eac7c880c1138ce073567a48aac9dfccf5822984/app/views/layouts/base.html#L11. Investigate what happened and solve it.

**Comment by pwalsh** [comment]
@akariv can you please fix.

**Comment by akariv** [comment]
There was never such a file, who knows why it was added in the first place (probably copied from another place).

I removed that reference.
