### ISSUE TITLE
Duplicate key error when try to create a datapackage using apparently fine dataset

### ISSUE THREAD

**Issue by jbothma** [openspending/openspending#1397]
![packager-epre-subprogrammes](https://user-images.githubusercontent.com/235801/46619154-ad7fe700-cb21-11e8-937a-afaf817e3bb1.png)

```
dump.to_sql
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "b9d2af843f3a7ca223eea07fb608e62aa23eeb2d03de0cb6_pkey"
DETAIL:  Key (activity_id, administrative_classification_id, date_id, geo_source_id, phase_id)=(831, 37, 1, 4, 1) already exists.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/dump/to_sql.py", line 144, in <module>
    SQLDumper()()
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 47, in __call__
    finalizer=self.finalize
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 69, in spew
    for rec in res:
  File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/lib/dump/dumper_base.py", line 122, in row_counter
    for row in resource:
  File "/usr/local/lib/python3.6/site-packages/tableschema_sql/writer.py", line 49, in write
    for wr in self.__insert():
  File "/usr/local/lib/python3.6/site-packages/tableschema_sql/writer.py", line 80, in __insert
    statement.execute(self.__buffer)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/base.py", line 386, in execute
    return e._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "b9d2af843f3a7ca223eea07fb608e62aa23eeb2d03de0cb6_pkey"
DETAIL:  Key (activity_id, administrative_classification_id, date_id, geo_source_id, phase_id)=(831, 37, 1, 4, 1) already exists.
 [SQL: 'INSERT INTO b9d2af843f3a7ca223eea07fb608e62aa23eeb2d03de0cb6 (amount, activity_id, administrative_classification_id, date_id, geo_source_id, phase_id) VALUES (%(amount)s, %(activity_id)s, %(administrative_classification_id)s, %(date_id)s, %(geo_source_id)s, %(phase_id)s)'] [parameters: ({'amount': Decimal('0'), 'activity_id': 591, 'administrative_classification_id': 31, 'date_id': 2, 'geo_source_id': 3, 'phase_id': 2}, {'amount': Decimal('0'), 'activity_id': 591, 'administrative_classification_id': 31, 'date_id': 3, 'geo_source_id': 3, 'phase_id': 2}, {'amount': Decimal('59999.9720688'), 'activity_id': 592, 'administrative_classification_id': 31, 'date_id': 1, 'geo_source_id': 3, 'phase_id': 1}, {'amount': Decimal('60000'), 'activity_id': 592, 'administrative_classification_id': 31, 'date_id': 2, 'geo_source_id': 3, 'phase_id': 2}, {'amount': Decimal('60000'), 'activity_id': 592, 'administrative_classification_id': 31, 'date_id': 3, 'geo_source_id': 3, 'phase_id': 2}, {'amount': Decimal('105811.2162552'), 'activity_id': 593, 'administrative_classification_id': 31, 'date_id': 1, 'geo_source_id': 3, 'phase_id': 1}, {'amount': Decimal('111726'), 'activity_id': 593, 'administrative_classification_id': 31, 'date_id': 2, 'geo_source_id': 3, 'phase_id': 2}, {'amount': Decimal('117890'), 'activity_id': 593, 'administrative_classification_id': 31, 'date_id': 3, 'geo_source_id': 3, 'phase_id': 2}  ... displaying 10 of 1001 total bound parameter sets ...  {'amount': Decimal('34433'), 'activity_id': 737, 'administrative_classification_id': 46, 'date_id': 2, 'geo_source_id': 4, 'phase_id': 2}, {'amount': Decimal('36327'), 'activity_id': 737, 'administrative_classification_id': 46, 'date_id': 3, 'geo_source_id': 4, 'phase_id': 2})] (Background on this error at: http://sqlalche.me/e/gkpj)
```
https://gist.githubusercontent.com/jbothma/9316ae05b96e10c50751c45c2187c4bd/raw/bae9b395028f7614f4a995170bf129049a043d0d/epre-subprogrammes-2018-19-from-jonathan.csv

**Comment by jbothma** [comment]
I actually did have duplicate rows, forgot to ignore amount column when checking dupes locally.
