### ISSUE TITLE
b.done is not a function (Packager)

### ISSUE THREAD

**Issue by stevage** [openspending/openspending#946]
I'm getting this error when running `gulp`:

```
TypeError: b.done is not a function
    at http://127.0.0.1/vendor.js?14608058944937894:397:248
    at r.$digest (http://127.0.0.1/vendor.js?14608058944937894:211:68)
    at http://127.0.0.1/vendor.js?14608058944937894:212:400
    at e (http://127.0.0.1/vendor.js?14608058944937894:122:305)
    at Window.<anonymous> (http://127.0.0.1/vendor.js?14608058944937894:125:181)
    at Window.window._evaluate (/Users/stevebennett/Dropbox/dev/OpenEconomy/OpenSpending/fiscal-data-packager/node_modules/zombie/lib/document.js:253:155)
    at /Users/stevebennett/Dropbox/dev/OpenEconomy/OpenSpending/fiscal-data-packager/node_modules/zombie/lib/eventloop.js:77:35
    at Immediate._onImmediate (/Users/stevebennett/Dropbox/dev/OpenEconomy/OpenSpending/fiscal-data-packager/node_modules/zombie/lib/eventloop.js:676:13)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

It also turns up in the Chrome console:

```
vendor.js:186 TypeError: b.done is not a function
    at vendor.js:397
    at r.$digest (vendor.js:211)
    at vendor.js:212
    at e (vendor.js:122)
    at vendor.js:125
```

**Comment by kravets-levko** [comment]
Hi @stevage! Can you provide step to reproduce this issue? It would have really helped me. Thanks!

**Comment by stevage** [comment]
Hmm, I got this when just doing:

- git checkout
- npm install
- gulp

Nothing special.

**Comment by kravets-levko** [comment]
Hi @stevage! Thank you for reply. I tried to reproduce it, but have no much results. May I ask you to send me entire `/app` directory (with `/app/public` subdir) somehow? You can send it to my email `levko.ne@gmail.com`. Thank you!

**Comment by akariv** [comment]
@stevage, is this still an issue?

**Comment by akariv** [comment]
Okay, closing for now - please reopen if this is still happening.
